/**
  ******************************************************************************
  * @file           : usb_mode.c
  * @brief          : USB CDC/MSC runtime mode switching (user-owned)
  ******************************************************************************
  * @attention
  *
  * This file is NOT generated by STM32CubeMX and is never touched by code
  * regeneration. It owns:
  *
  *   1. The CDC/MSC mode state machine and the runtime class switch.
  *   2. MSC_Desc, a second USB descriptor set used while enumerated as MSC.
  *      Passing this to USBD_Init() replaces the old approach of patching the
  *      CDC descriptors at runtime from inside usbd_desc.c, so usbd_desc.c can
  *      stay exactly as CubeMX generates it.
  *   3. USBD_static_malloc(), sized for the LARGER of the MSC and CDC class
  *      handles. See the note above that function.
  *
  * usb_device.c keeps only what CubeMX generates: hUsbDeviceFS and a
  * CDC-only MX_USB_Device_Init(). The device always boots in CDC mode, so
  * the stock generated init body is exactly correct and needs no override.
  *
  * There are deliberately no user-code fences in this file.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "usb_mode.h"
#include "usb_device.h"
#include "usbd_core.h"
#include "usbd_desc.h"
#include "usbd_cdc.h"
#include "usbd_cdc_if.h"
#include "usbd_msc.h"
#include "usbd_msc_bot.h"
#include "usbd_storage_if.h"

/* External references -------------------------------------------------------*/
/* Defined by CubeMX in USB_Device/App/usb_device.c */
extern USBD_HandleTypeDef hUsbDeviceFS;

/* Defined by CubeMX in USB_Device/App/usbd_desc.c. The three CDC string
 * callbacks below are mode-independent, so MSC_Desc reuses them verbatim
 * rather than duplicating them. They are non-static in usbd_desc.c but are
 * not declared in usbd_desc.h, hence the explicit prototypes. */
extern USBD_DescriptorsTypeDef CDC_Desc;
extern uint8_t *USBD_CDC_LangIDStrDescriptor(USBD_SpeedTypeDef speed, uint16_t *length);
extern uint8_t *USBD_CDC_ManufacturerStrDescriptor(USBD_SpeedTypeDef speed, uint16_t *length);
extern uint8_t *USBD_CDC_SerialStrDescriptor(USBD_SpeedTypeDef speed, uint16_t *length);
extern uint8_t  USBD_StrDesc[USBD_MAX_STR_DESC_SIZ];

/* Private defines -----------------------------------------------------------*/
/* Mirror of the MSC-side values that used to live as private defines in
 * usbd_desc.c. The VID must match USBD_VID there; if you ever change it,
 * change it in both places. */
#define USB_MODE_VID                    1155
#define USB_MODE_MSC_PID                22337
#define USB_MODE_MSC_PRODUCT_STRING     "FRIENDS SD Mass Storage"
#define USB_MODE_MSC_CONFIG_STRING      "MSC Config"
#define USB_MODE_MSC_INTERFACE_STRING   "MSC Interface"

/* MSC descriptor set --------------------------------------------------------*/
#if defined ( __ICCARM__ ) /* IAR Compiler */
  #pragma data_alignment=4
#endif /* defined ( __ICCARM__ ) */
/** USB standard device descriptor, MSC variant.
  * Identical to USBD_CDC_DeviceDesc except that class/subclass/protocol are
  * 0x00 (defined per-interface, as MSC requires) and the product ID is the
  * MSC one. This reproduces byte-for-byte what the old runtime patching in
  * USBD_CDC_DeviceDescriptor() produced. */
__ALIGN_BEGIN static uint8_t MSC_DeviceDesc[USB_LEN_DEV_DESC] __ALIGN_END =
{
  0x12,                          /* bLength */
  USB_DESC_TYPE_DEVICE,          /* bDescriptorType */
  0x00,                          /* bcdUSB */
  0x02,
  0x00,                          /* bDeviceClass    - per-interface */
  0x00,                          /* bDeviceSubClass - per-interface */
  0x00,                          /* bDeviceProtocol - per-interface */
  USB_MAX_EP0_SIZE,              /* bMaxPacketSize */
  LOBYTE(USB_MODE_VID),          /* idVendor */
  HIBYTE(USB_MODE_VID),
  LOBYTE(USB_MODE_MSC_PID),      /* idProduct */
  HIBYTE(USB_MODE_MSC_PID),
  0x00,                          /* bcdDevice rel. 2.00 */
  0x02,
  USBD_IDX_MFC_STR,              /* Index of manufacturer string */
  USBD_IDX_PRODUCT_STR,          /* Index of product string */
  USBD_IDX_SERIAL_STR,           /* Index of serial number string */
  USBD_MAX_NUM_CONFIGURATION     /* bNumConfigurations */
};

static uint8_t *MSC_DeviceDescriptor(USBD_SpeedTypeDef speed, uint16_t *length)
{
  UNUSED(speed);
  *length = sizeof(MSC_DeviceDesc);
  return MSC_DeviceDesc;
}

static uint8_t *MSC_ProductStrDescriptor(USBD_SpeedTypeDef speed, uint16_t *length)
{
  UNUSED(speed);
  USBD_GetString((uint8_t *)USB_MODE_MSC_PRODUCT_STRING, USBD_StrDesc, length);
  return USBD_StrDesc;
}

static uint8_t *MSC_ConfigStrDescriptor(USBD_SpeedTypeDef speed, uint16_t *length)
{
  UNUSED(speed);
  USBD_GetString((uint8_t *)USB_MODE_MSC_CONFIG_STRING, USBD_StrDesc, length);
  return USBD_StrDesc;
}

static uint8_t *MSC_InterfaceStrDescriptor(USBD_SpeedTypeDef speed, uint16_t *length)
{
  UNUSED(speed);
  USBD_GetString((uint8_t *)USB_MODE_MSC_INTERFACE_STRING, USBD_StrDesc, length);
  return USBD_StrDesc;
}

USBD_DescriptorsTypeDef MSC_Desc =
{
  MSC_DeviceDescriptor,
  USBD_CDC_LangIDStrDescriptor,       /* mode-independent, reused */
  USBD_CDC_ManufacturerStrDescriptor, /* mode-independent, reused */
  MSC_ProductStrDescriptor,
  USBD_CDC_SerialStrDescriptor,       /* mode-independent, reused */
  MSC_ConfigStrDescriptor,
  MSC_InterfaceStrDescriptor
};

/* Mode state ----------------------------------------------------------------*/
static USB_DeviceModeTypeDef usb_device_mode = USB_DEVICE_MODE_CDC;
static volatile uint8_t usb_msc_ejected = 0U;
static volatile uint8_t usb_switch_to_cdc_pending = 0U;
/* 0=no message, 1=SCSI eject triggered restore, 2=disconnect timeout triggered restore */
static volatile uint8_t usb_cdc_restore_reason = 0U;
/* Suspend-based disconnect detection: track whether MSC was ever fully configured */
static uint32_t msc_suspend_detect_ms = 0U;
static uint8_t msc_was_configured = 0U;

/* Private functions ---------------------------------------------------------*/
static uint8_t USB_Device_InitClass(USB_DeviceModeTypeDef mode)
{
  if (mode == USB_DEVICE_MODE_MSC) {
    if (USBD_Init(&hUsbDeviceFS, &MSC_Desc, DEVICE_FS) != USBD_OK) {
      return 0U;
    }
    if (USBD_RegisterClass(&hUsbDeviceFS, &USBD_MSC) != USBD_OK) {
      return 0U;
    }
    if (USBD_MSC_RegisterStorage(&hUsbDeviceFS, &USBD_Storage_Interface_fops_FS) != USBD_OK) {
      return 0U;
    }
  } else {
    if (USBD_Init(&hUsbDeviceFS, &CDC_Desc, DEVICE_FS) != USBD_OK) {
      return 0U;
    }
    if (USBD_RegisterClass(&hUsbDeviceFS, &USBD_CDC) != USBD_OK) {
      return 0U;
    }
    if (USBD_CDC_RegisterInterface(&hUsbDeviceFS, &USBD_Interface_fops_FS) != USBD_OK) {
      return 0U;
    }
  }

  if (USBD_Start(&hUsbDeviceFS) != USBD_OK) {
    return 0U;
  }

  return 1U;
}

/* Exported functions --------------------------------------------------------*/
void USB_Device_SetMode(USB_DeviceModeTypeDef mode)
{
  usb_device_mode = mode;
  if (mode == USB_DEVICE_MODE_CDC) {
    usb_msc_ejected = 0U;
    usb_switch_to_cdc_pending = 0U;
  }
}

USB_DeviceModeTypeDef USB_Device_GetMode(void)
{
  return usb_device_mode;
}

uint8_t USB_Device_SwitchToMSC(void)
{
  usb_device_mode = USB_DEVICE_MODE_MSC;
  usb_msc_ejected = 0U;
  usb_switch_to_cdc_pending = 0U;
  usb_cdc_restore_reason = 0U;
  msc_suspend_detect_ms = 0U;
  msc_was_configured = 0U;
  (void)USBD_Stop(&hUsbDeviceFS);
  (void)USBD_DeInit(&hUsbDeviceFS);
  HAL_Delay(250U);
  if (USB_Device_InitClass(USB_DEVICE_MODE_MSC) != 0U) {
    return 1U;
  }

  usb_device_mode = USB_DEVICE_MODE_CDC;
  (void)USBD_DeInit(&hUsbDeviceFS);
  HAL_Delay(100U);
  return USB_Device_InitClass(USB_DEVICE_MODE_CDC);
}

void USB_Device_NotifyMSCEjected(void)
{
  if (usb_device_mode == USB_DEVICE_MODE_MSC) {
    usb_msc_ejected = 1U;
  }
}

void USB_Device_NotifyDisconnected(void)
{
  if (usb_device_mode == USB_DEVICE_MODE_MSC) {
    usb_msc_ejected = 0U;
    usb_switch_to_cdc_pending = 1U;
  }
}

void USB_Device_Service(void)
{
  /* Path 1: host sent SCSI START STOP UNIT eject — switch immediately */
  if (usb_msc_ejected != 0U) {
    usb_msc_ejected = 0U;
    usb_switch_to_cdc_pending = 1U;
    usb_cdc_restore_reason = 1U;
  }

  /* Path 2: physical disconnect fallback — bus stays suspended > 5 s after
   * MSC was at least once fully enumerated; guards against premature trigger
   * before the host has seen the MSC device for the first time */
  if ((usb_device_mode == USB_DEVICE_MODE_MSC) && (usb_switch_to_cdc_pending == 0U)) {
    if (hUsbDeviceFS.dev_state == USBD_STATE_CONFIGURED) {
      msc_was_configured = 1U;
      msc_suspend_detect_ms = 0U;
    } else if ((msc_was_configured != 0U) && (hUsbDeviceFS.dev_state == USBD_STATE_SUSPENDED)) {
      if (msc_suspend_detect_ms == 0U) {
        msc_suspend_detect_ms = HAL_GetTick();
        if (msc_suspend_detect_ms == 0U) {
          msc_suspend_detect_ms = 1U;
        }
      } else if ((HAL_GetTick() - msc_suspend_detect_ms) >= 5000U) {
        msc_suspend_detect_ms = 0U;
        usb_switch_to_cdc_pending = 1U;
        usb_cdc_restore_reason = 2U;
      }
    } else {
      msc_suspend_detect_ms = 0U;
    }
  }

  if (usb_switch_to_cdc_pending != 0U) {
    usb_switch_to_cdc_pending = 0U;
    usb_msc_ejected = 0U;
    msc_suspend_detect_ms = 0U;
    msc_was_configured = 0U;
    usb_device_mode = USB_DEVICE_MODE_CDC;
    (void)USBD_Stop(&hUsbDeviceFS);
    (void)USBD_DeInit(&hUsbDeviceFS);
    HAL_Delay(100U);
    if (USB_Device_InitClass(USB_DEVICE_MODE_CDC) == 0U) {
      usb_cdc_restore_reason = 0U;  /* Init failed; suppress restored message */
    }
  }
}

/* Returns 0 if no message is ready, 1 if restored after SCSI eject,
 * 2 if restored after physical disconnect timeout. */
uint8_t USB_Device_TakeCDCRestoredMessage(void)
{
  if (usb_cdc_restore_reason == 0U) {
    return 0U;
  }
  if ((usb_device_mode != USB_DEVICE_MODE_CDC) || (hUsbDeviceFS.dev_state != USBD_STATE_CONFIGURED)) {
    return 0U;
  }
  uint8_t reason = usb_cdc_restore_reason;
  usb_cdc_restore_reason = 0U;
  return reason;
}

/**
  * @brief  Static single allocation for the active USB class handle.
  *
  * IMPORTANT — this deliberately replaces the USBD_static_malloc() that
  * CubeMX generates in USB_Device/Target/usbd_conf.c. CubeMX only knows about
  * CDC, so its version sizes the buffer for USBD_CDC_HandleTypeDef alone,
  * which is too small for USBD_MSC_BOT_HandleTypeDef. That failure is silent:
  * it compiles clean and then overruns the buffer the first time the device
  * switches to MSC.
  *
  * After every CubeMX regeneration the generated copy comes back and the
  * build fails with a duplicate definition of USBD_static_malloc. That link
  * error IS the reminder: delete the regenerated copy from usbd_conf.c and
  * keep this one.
  *
  * @param  size: Size of allocated memory (unused, single static allocation)
  * @retval Pointer to the static buffer
  */
void *USBD_static_malloc(uint32_t size)
{
  UNUSED(size);
  static uint32_t mem[((sizeof(USBD_MSC_BOT_HandleTypeDef) > sizeof(USBD_CDC_HandleTypeDef)) ?
      sizeof(USBD_MSC_BOT_HandleTypeDef) : sizeof(USBD_CDC_HandleTypeDef)) / 4U + 1U];/* On 32-bit boundary */
  return mem;
}
