/**
  ******************************************************************************
  * @file           : usb_mode.h
  * @brief          : USB CDC/MSC runtime mode switching (user-owned)
  ******************************************************************************
  * @attention
  *
  * This file is NOT generated by STM32CubeMX and is never touched by code
  * regeneration. All custom USB class-switching logic lives here so that
  * USB_Device/App/usb_device.c and usbd_desc.c can stay pristine.
  *
  * There are deliberately no user-code fences in this file. Fences imply
  * CubeMX ownership, which is the opposite of why this file exists.
  *
  * usb_device.h pulls this header in via its INCLUDE fence, so every existing
  * consumer of usb_device.h keeps compiling unchanged.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef USB_MODE_H
#define USB_MODE_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "usbd_def.h"

/* Exported types ------------------------------------------------------------*/
typedef enum {
  USB_DEVICE_MODE_CDC = 0,
  USB_DEVICE_MODE_MSC = 1
} USB_DeviceModeTypeDef;

/* Exported variables --------------------------------------------------------*/
/**
  * Descriptor set served while the device is enumerated as MSC. Defined in
  * usb_mode.c and passed to USBD_Init() on the MSC path, which keeps
  * usbd_desc.c free of any mode-dependent branching.
  */
extern USBD_DescriptorsTypeDef MSC_Desc;

/* Exported functions prototypes ---------------------------------------------*/
void                  USB_Device_SetMode(USB_DeviceModeTypeDef mode);
USB_DeviceModeTypeDef USB_Device_GetMode(void);
uint8_t               USB_Device_SwitchToMSC(void);
void                  USB_Device_NotifyMSCEjected(void);
void                  USB_Device_NotifyDisconnected(void);
void                  USB_Device_Service(void);
uint8_t               USB_Device_TakeCDCRestoredMessage(void);

#ifdef __cplusplus
}
#endif

#endif /* USB_MODE_H */
